# Exploratory Data Analysis (Day 02)

## import librarise and setup

In [52]:
#EDA 
import numpy as np
import pandas as pd
# time stamp for last update to maintain the records of updates
import time as t
print('Last Update:',t.asctime())



#filter warnings (to ignore warning from third party librariese)
import warnings as w
w.filterwarnings('ignore')

#set random seed (Setup random seed to ingone the redundancy in random data)
np.random.seed(42)

Last Update: Sat Oct 10 22:57:20 2026

## Dataset

### Generate Data Using numpy

In [53]:
names =np.char.add('std',np.arange(1,101).astype('str'))
names[:10]

array(['std1', 'std2', 'std3', 'std4', 'std5', 'std6', 'std7', 'std8',
       'std9', 'std10'], dtype='<U24')

In [54]:
ages=np.random.randint(18,40,100)
ages[:10]

array([24, 37, 32, 28, 25, 38, 24, 36, 28, 28], dtype=int32)

In [55]:
gender=np.random.choice(['Male','Female'],100)
gender

array(['Male', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female',
       'Male', 'Male', 'Female', 'Female', 'Female', 'Male', 'Female',
       'Male', 'Male', 'Female', 'Female', 'Male', 'Male', 'Female',
       'Female', 'Female', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male',
       'Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Male',
       'Female', 'Male', 'Male', 'Male', 'Male', 'Male', 'Female',
       'Female', 'Female', 'Male', 'Male', 'Male', 'Female', 'Male',
       'Male', 'Female', 'Male', 'Female', 'Female', 'Female', 'Male',
       'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Female', 'Male',
       'Female', 'Male', 'Male', 'Male', 'Female', 'Female', 'Female',
       'Female', 'Male', 'Female', 'Male', 'Male', 'Female', 'Female',
       'Female', 'Female', 'Female', 'Female', 'Female', 'Female', 'Male',
       'Female', 'Female', 'Male', 'Female', 'Male', 'Male', 'Female',
       'Male', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female'],
      dtype='<U6')

In [56]:
ml_100=np.random.randint(20,100,100)
dl_100=np.random.randint(10,100,100)
nlp_100=np.random.randint(40,100,100)
eda_60=np.random.randint(50,61,100)

In [57]:
p1 = np.random.randint(1000, 99999, 100).astype(str)
p2 = np.random.randint(1000000, 9999999, 100).astype(str)
p3 = np.random.randint(0, 10, 100).astype(str)

p1 = np.char.add(p1, '-')
p2 = np.char.add(p1, p2)
p3 = np.char.add('-', p3)

cnic = np.char.add(p2, p3)

cnic[:1]

array(['61921-3373139-1'], dtype='<U35')

### introduce null values in data

In [58]:
cnic[np.random.randint(0,100,5)]=None
cnic

array(['61921-3373139-1', '6486-6221816-3', '9335-3114792-8',
       '87900-9441136-5', '90112-2873421-0', '98203-7550670-7',
       '12130-7081950-6', '88508-7925877-9', '61566-6967106-2', 'None',
       '28192-8177545-4', '2062-6122783-3', '85076-6528983-9',
       '90780-1160775-7', '22545-8349369-0', '22689-3667867-9',
       '12174-7655623-0', 'None', '10348-7978737-7', '24714-2344027-4',
       '39102-5166500-1', '75460-8467048-5', '90930-8884479-4',
       '7801-1497562-1', '73267-5578238-2', '49136-5037776-8',
       '24625-5010912-6', '83873-5511732-6', '73592-6562067-5',
       '78052-6237196-7', '45261-5885211-3', '2542-7126319-7',
       '22677-2600396-3', '47732-4311149-7', '51343-9511010-8',
       '40081-3496081-2', '63856-1575278-2', '94105-6187480-1',
       '89858-2178049-9', '20065-4080201-2', '84460-8136029-2',
       '89092-4464442-4', '55693-4314692-4', '27962-5719607-1',
       '29295-7285088-9', '14807-2110389-5', '43348-9416320-4',
       '27432-4912942-5', '84285-9501424-0', '92792-8468810-4',
       '58854-2635156-8', '41262-9523838-9', '38080-6001045-1',
       '2324-5463418-0', '92267-5345760-9', '36909-8153768-8',
       '90339-4251298-9', '20870-5465150-8', '35578-9389012-8',
       '73124-8249903-5', '27790-5897590-7', '26289-7189573-0',
       '56129-2323483-9', '94714-2722320-3', '95246-3332517-0',
       '16485-4196340-7', 'None', 'None', '5748-6692493-3',
       '87769-9247752-7', '10435-2087341-5', '4709-7195200-9',
       '31355-4977266-6', '56771-6558956-7', '58799-4031756-1',
       '14116-1843523-9', '26470-9934845-7', '43344-5040479-2',
       '43918-1092193-6', '53224-2186887-2', '40298-9896761-6',
       '81219-4334817-1', '62629-3715514-9', '67040-3658571-5',
       '29016-5834357-2', '24960-8102173-2', '34591-5892472-8',
       '83848-1481680-6', '68641-6165679-4', '37395-7180142-9',
       '23700-6287118-6', '35620-5100673-8', '21559-2534026-0',
       '94045-9704434-6', '94396-4467366-5', '62642-1327359-9',
       '77539-1317537-8', '22732-7953757-0', '92362-1550222-3', 'None'],
      dtype='<U35')

## Convert it into Dictionary

In [59]:
data={
    "Name":names,
    'Age':ages,
    'Gender':gender,
    'CNIC':cnic,
    'Machine Learning':ml_100,
    'Deep Learning':dl_100,
    'Nlp':nlp_100,
    'EDA':eda_60
}

## convert into data frame

In [60]:
df=pd.DataFrame(data)
df.head()

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,Nlp,EDA
0,std1,24,Male,61921-3373139-1,96,70,64,53
1,std2,37,Male,6486-6221816-3,22,50,97,50
2,std3,32,Female,9335-3114792-8,89,42,61,54
3,std4,28,Male,87900-9441136-5,91,77,97,56
4,std5,25,Female,90112-2873421-0,46,42,97,59

In [61]:
df.to_csv('student_records.csv',index=False)

## Exploratory Data Analysis

In [62]:
df=pd.read_csv('student_records.csv')
df.head()

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,Nlp,EDA
0,std1,24,Male,61921-3373139-1,96,70,64,53
1,std2,37,Male,6486-6221816-3,22,50,97,50
2,std3,32,Female,9335-3114792-8,89,42,61,54
3,std4,28,Male,87900-9441136-5,91,77,97,56
4,std5,25,Female,90112-2873421-0,46,42,97,59

## Advance EDA

### Select COlumn from dataset

In [63]:
# select age and gender first(3 columns)
df[['Age','Gender']][:3]

   Age  Gender
0   24    Male
1   37    Male
2   32  Female

In [67]:
df.iloc[20:24]

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,Nlp,EDA
20,std21,38,Female,39102-5166500-1,21,47,83,56
21,std22,18,Female,75460-8467048-5,22,60,44,51
22,std23,29,Female,90930-8884479-4,75,63,78,50
23,std24,39,Male,7801-1497562-1,78,17,43,60

### filter recors from data

In [68]:
df[df['Age']>25]

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,Nlp,EDA
1,std2,37,Male,6486-6221816-3,22,50,97,50
2,std3,32,Female,9335-3114792-8,89,42,61,54
3,std4,28,Male,87900-9441136-5,91,77,97,56
5,std6,38,Male,98203-7550670-7,28,23,61,59
7,std8,36,Male,88508-7925877-9,56,57,91,54
...,...,...,...,...,...,...,...,...
89,std90,26,Female,37395-7180142-9,43,25,69,55
91,std92,29,Male,35620-5100673-8,91,85,91,52
93,std94,28,Male,94045-9704434-6,57,24,51,53
94,std95,36,Male,94396-4467366-5,44,75,55,58
95,std96,34,Male,62642-1327359-9,37,41,65,52

In [69]:
df[df['Machine Learning']>90]

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,Nlp,EDA
0,std1,24,Male,61921-3373139-1,96,70,64,53
3,std4,28,Male,87900-9441136-5,91,77,97,56
11,std12,21,Female,2062-6122783-3,98,76,93,59
37,std38,38,Male,94105-6187480-1,94,58,99,59
46,std47,19,Male,43348-9416320-4,92,62,94,57
49,std50,24,Male,92792-8468810-4,99,94,65,59
83,std84,30,Female,67040-3658571-5,99,66,68,52
90,std91,18,Male,23700-6287118-6,94,23,85,60
91,std92,29,Male,35620-5100673-8,91,85,91,52
99,std100,18,Female,NaN,99,60,78,52

In [70]:
df[df['Nlp']<30]

Empty DataFrame
Columns: [Name, Age, Gender, CNIC, Machine Learning, Deep Learning, Nlp, EDA]
Index: []

###  Values Count (gnder)

In [71]:
df['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [72]:
df['Gender'].value_counts()

Gender
Male      56
Female    44
Name: count, dtype: int64

In [75]:
(df['EDA'].value_counts()>1).sum()

np.int64(11)

In [76]:
df['Age'].value_counts()

Age
32    8
25    8
38    8
29    7
24    6
21    6
20    5
19    5
35    5
28    4
36    4
39    4
18    4
26    4
31    4
37    3
34    3
27    3
33    3
30    3
23    2
22    1
Name: count, dtype: int64

In [77]:
df.isna().sum()

Name                0
Age                 0
Gender              0
CNIC                5
Machine Learning    0
Deep Learning       0
Nlp                 0
EDA                 0
dtype: int64

In [78]:
df.dropna(inplace=True)

In [79]:
df.isna().sum()

Name                0
Age                 0
Gender              0
CNIC                0
Machine Learning    0
Deep Learning       0
Nlp                 0
EDA                 0
dtype: int64

In [80]:
df.isna().sum().sum()

np.int64(0)

### Feature Engineering

In [81]:
df['Obtained Marks']=df['Machine Learning']+df['Deep Learning']+df['Nlp']+df['EDA']
df.head(1)

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,Nlp,EDA,Obtained Marks
0,std1,24,Male,61921-3373139-1,96,70,64,53,283

In [84]:
df['Percentage']=(df['Obtained Marks']*100/100).round(2)
df.head(1)

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,Nlp,EDA,Obtained Marks,Percentage
0,std1,24,Male,61921-3373139-1,96,70,64,53,283.0,283.0

In [85]:
df['Average']=(df['Obtained Marks']/4).round(2)
df.head(1)

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,Nlp,EDA,Obtained Marks,Percentage,Average
0,std1,24,Male,61921-3373139-1,96,70,64,53,283.0,283.0,70.75

In [89]:
def check_status(x):
    if(x>50):
        return 'Passed'
    else:
        return 'Failed'

In [90]:
df['Status']=df['Percentage'].apply(check_status)
df.head(1)

,Name,Age,Gender,CNIC,Machine Learning,Deep Learning,Nlp,EDA,Obtained Marks,Percentage,Average,Status
0,std1,24,Male,61921-3373139-1,96,70,64,53,283.0,283.0,70.75,Passed

In [91]:
df['Deep Learning'].max()

np.int64(99)

In [92]:
# max marks w.r.t gender in subject
df.groupby('Gender')['Deep Learning'].max()

Gender
Female    96
Male      99
Name: Deep Learning, dtype: int64

In [93]:
# min marks w.r.t gender in subject
df.groupby('Gender')['Deep Learning'].min()

Gender
Female    15
Male      13
Name: Deep Learning, dtype: int64

In [102]:
df.sum()      # sum of each column
# df.mean()     # average
# df.median()   # median
df.min()      # minimum
df.max()      # maximum
df.count()    # count non-null values
df.size       # total elements (including NaN)
df.nunique()  # count distinct values

Name                95
Age                 22
Gender               2
CNIC                95
Machine Learning    50
Deep Learning       59
Nlp                 47
EDA                 11
Obtained Marks      74
Percentage          74
Average             74
Status               1
dtype: int64

### Save CSV

In [103]:
df.to_csv('student_records_update.csv')