# Numpy in Python

In [3]:
!pip install numpy

Requirement already satisfied: numpy in C:\Users\Mega Providers\miniconda3\Lib\site-packages (2.5.3)

In [4]:
import numpy as np

# Creating Array

In [5]:
arr1=np.array([1,2,3,4,5])

In [6]:
type(arr1)

numpy.ndarray

# Array Dimensiin

In [7]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr4 = np.array([[10, 20], [30, 40], [50, 60]])

arr1.ndim,arr2.ndim,arr3.ndim,arr4.ndim

(1, 2, 3, 2)

In [8]:
arr1.shape,arr2.shape,arr3.shape,arr4.shape

((5,), (2, 3), (2, 2, 2), (3, 2))

In [9]:
arr4 = np.array([
    [[1], [2], [3]],
    [[4], [5], [6]]
])

print(arr4)
print(arr4.shape)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
(2, 3, 1)

# Shape and Reshape

In [10]:
arr1=np.array([1,2,3,4])

In [11]:
arr1.ndim

1

In [12]:
arr1.shape

(4,)

In [13]:
arr2=arr1.reshape((2,2))

In [14]:
arr1.shape,arr2.shape

((4,), (2, 2))

## array operations

In [15]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([9,7,6,8,7,6])
arr1+arr2

array([10,  9,  9, 12, 12, 12])

In [16]:
# you can use any arithmatic operator on this

# Array Methods

In [17]:
np.zeros((3))

array([0., 0., 0.])

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.zeros((3,4),dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
np.zeros((1000,1000),dtype='int')

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1000, 1000))

In [21]:
np.zeros((2,2,2,2),dtype='int')

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]])

In [22]:
np.ones((2,3,4),dtype='int')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [23]:
np.eye(4,dtype='int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [24]:
np.arange(10,100,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [25]:
np.arange(1000001,1010001)

array([1000001, 1000002, 1000003, ..., 1009998, 1009999, 1010000],
      shape=(10000,))

In [26]:
# to distrubute number equally
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## Random Module in numpy

In [27]:
np.random.random(10)

array([0.43697206, 0.87171942, 0.67972829, 0.45379037, 0.58246968,
       0.22250465, 0.09512965, 0.39136666, 0.71017367, 0.62998199])

In [28]:
np.random.random((4,4))

array([[0.54392487, 0.98077549, 0.09739934, 0.37257645],
       [0.64638907, 0.11444434, 0.41667668, 0.70326951],
       [0.14115408, 0.61464883, 0.751265  , 0.34731129],
       [0.82943483, 0.20143243, 0.53073116, 0.61973687]])

In [29]:
np.random.randint(18,40,10)

array([39, 21, 37, 35, 35, 26, 29, 24, 33, 36], dtype=int32)

In [30]:
marks=np.random.randint(70,100,100)

In [31]:
marks

array([87, 97, 94, 82, 89, 70, 71, 88, 85, 98, 92, 82, 87, 72, 85, 93, 91,
       74, 89, 74, 83, 90, 85, 88, 74, 86, 70, 92, 87, 94, 73, 96, 92, 97,
       98, 70, 84, 73, 86, 79, 73, 70, 89, 80, 82, 93, 86, 71, 74, 74, 99,
       92, 85, 88, 91, 75, 70, 86, 76, 95, 99, 77, 73, 73, 84, 82, 89, 92,
       94, 83, 93, 73, 83, 99, 95, 82, 70, 97, 95, 71, 73, 80, 80, 92, 73,
       79, 83, 70, 88, 75, 71, 77, 94, 96, 75, 98, 91, 86, 73, 87],
      dtype=int32)

In [32]:
gender=['Male','Female']
np.random.choice(gender,100)

array(['Female', 'Male', 'Female', 'Male', 'Male', 'Female', 'Male',
       'Male', 'Male', 'Female', 'Female', 'Male', 'Male', 'Male', 'Male',
       'Female', 'Female', 'Male', 'Male', 'Male', 'Female', 'Female',
       'Female', 'Male', 'Female', 'Female', 'Female', 'Female', 'Female',
       'Female', 'Female', 'Male', 'Male', 'Male', 'Male', 'Female',
       'Male', 'Female', 'Female', 'Female', 'Female', 'Female', 'Female',
       'Male', 'Female', 'Female', 'Male', 'Male', 'Female', 'Female',
       'Male', 'Female', 'Male', 'Female', 'Male', 'Male', 'Male',
       'Female', 'Male', 'Female', 'Female', 'Female', 'Male', 'Female',
       'Female', 'Female', 'Male', 'Male', 'Female', 'Female', 'Male',
       'Male', 'Female', 'Female', 'Male', 'Female', 'Female', 'Male',
       'Male', 'Male', 'Female', 'Female', 'Male', 'Female', 'Male',
       'Male', 'Female', 'Male', 'Male', 'Female', 'Female', 'Female',
       'Male', 'Female', 'Female', 'Female', 'Male', 'Male', 'Male',
       'Male'], dtype='<U6')

In [35]:
np.random.seed(42)
np.random.randint(18,40,10)

array([24, 37, 32, 28, 25, 38, 24, 36, 28, 28], dtype=int32)

# Task at numpy

In [36]:
arr = np.random.randint(1, 101, size=(3, 3))
print("3x3 Matrix:")
print(arr)

3x3 Matrix:
[[ 88 100  24]
 [  3  22  53]
 [  2  88  30]]

In [37]:
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

Maximum: 100
Minimum: 2
Mean: 45.55555555555556
Standard Deviation: 35.88906088710075

In [42]:
# Reshape the matrix into a 1D array
arr_1d = arr.reshape(9)

In [39]:
print("1D Array:")
print(arr_1d)

1D Array:
[ 88 100  24   3  22  53   2  88  30]

In [40]:
from statistics import mode

In [41]:
print("Mode:", mode(arr.flatten()))

Mode: 88

# Pandas in python

In [3]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Mega Providers\miniconda3\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\Mega Providers\miniconda3\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Mega Providers\miniconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Mega Providers\miniconda3\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\Mega Providers\miniconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [7]:
import pandas as pd

## Seriese

In [10]:
sr1=pd.Series([1,2,3,4,5,6])

In [11]:
sr1.shape

(6,)

In [12]:
sr1.dtype

dtype('int64')

## Data Frames

In [13]:
data={
    'name':['Ali','Ahmed','Usman','Umer'],
    'age':[23,24,23,22],
    'Marks':[97.5,87.5,88,47]
}

In [14]:
df= pd.DataFrame(data)

In [15]:
df

    name  age  Marks
0    Ali   23   97.5
1  Ahmed   24   87.5
2  Usman   23   88.0
3   Umer   22   47.0

## Reading dataframe from csv file

In [16]:
df=pd.read_csv('data.csv')
df

      Name  Age        City
0      Ali   18  Abbottabad
1     Sara   19   Islamabad
2    Ahmed   20      Lahore
3   Ayesha   18     Karachi
4    Usman   21  Abbottabad
5   Fatima   19   Islamabad
6    Bilal   22      Lahore
7   Zainab   20     Karachi
8   Hassan   18  Abbottabad
9   Maryam   21   Islamabad
10   Hamza   19      Lahore
11    Noor   20     Karachi
12    Saad   22  Abbottabad
13    Hira   18   Islamabad
14    Omar   20      Lahore
15    Iqra   19     Karachi
16  Danish   21  Abbottabad
17    Amna   22   Islamabad
18   Fahad   18      Lahore
19   Laiba   21     Karachi

In [17]:
# to show top values
df.head(2)

   Name  Age        City
0   Ali   18  Abbottabad
1  Sara   19   Islamabad

In [19]:
# to show  recorde from bottom
df.tail(2)

     Name  Age     City
18  Fahad   18   Lahore
19  Laiba   21  Karachi

In [20]:
# to show column  name
df.columns

Index(['Name', 'Age', 'City'], dtype='str')

In [21]:
# to show full info
df.info

<bound method DataFrame.info of       Name  Age        City
0      Ali   18  Abbottabad
1     Sara   19   Islamabad
2    Ahmed   20      Lahore
3   Ayesha   18     Karachi
4    Usman   21  Abbottabad
5   Fatima   19   Islamabad
6    Bilal   22      Lahore
7   Zainab   20     Karachi
8   Hassan   18  Abbottabad
9   Maryam   21   Islamabad
10   Hamza   19      Lahore
11    Noor   20     Karachi
12    Saad   22  Abbottabad
13    Hira   18   Islamabad
14    Omar   20      Lahore
15    Iqra   19     Karachi
16  Danish   21  Abbottabad
17    Amna   22   Islamabad
18   Fahad   18      Lahore
19   Laiba   21     Karachi>

In [26]:
df.describe()

            Age
count  20.00000
mean   19.80000
std     1.43637
min    18.00000
25%    18.75000
50%    20.00000
75%    21.00000
max    22.00000